# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b552e53e15af49f98c0696d2ed510c0a9c4e5c7f08b1e58a9e77e067ccb887136a343baee5f008a32f50f4eee4ebd746aa8230c85f54316d6a7faa99e37eb463

test:
  secret_key_base: c662153116bdfe3d81d910bbfe6355372757d5f4616bfc1306c51f35de9aa63e693c37092573af78b2ff7b6b29a14f819d581313624430ef2b3f025285f6fdf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
